# Generated by Django 5.0.3 on 2024-03-19 20:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registered_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 22, 27, 53, 863735)),
        ),
    ]
