# Generated by Django 5.0.3 on 2024-03-19 20:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_user_registered_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='registered_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 22, 34, 0, 586172)),
        ),
        migrations.AlterField(
            model_name='user',
            name='tall',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
