# Generated by Django 5.0.3 on 2024-03-19 20:56

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_user_id_alter_user_registered_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='registered_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 22, 56, 53, 314454)),
        ),
        migrations.AddField(
            model_name='user',
            name='dep_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='about.department'),
        ),
    ]
