# Generated by Django 5.0.3 on 2024-03-26 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_department_alter_user_registered_at_user_dep_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registered_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 26, 14, 7, 21, 112134)),
        ),
    ]
