# Generated by Django 5.0.3 on 2024-03-26 12:13

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_alter_department_id_alter_user_id_alter_user_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dep_id',
        ),
        migrations.AddField(
            model_name='user',
            name='dep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='about.department'),
        ),
        migrations.AlterField(
            model_name='user',
            name='registered_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 26, 14, 13, 16, 97939)),
        ),
    ]
